FROM alpine:3.8

RUN apk add --no-cache gcc git postgresql-dev musl-dev imagemagick zlib-dev jpeg-dev python3-dev py3-virtualenv freetype-dev build-base libc-dev libffi-dev libxml2-dev libxslt-dev lapack-dev gfortran && \
    pip3 install --upgrade pip

